### ISSUE TITLE
SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [Rightpoint/Anchorage#11]
Hi,
It's will be great to create a [Swift 3](https://swift.org/blog/swift-3-0-release-process/) version of your component 

Article about **Swift 3**: 
- [Migrating to Swift 2.3 or Swift 3 from Swift 2.2](https://swift.org/migration-guide/)

With [Swift 3](https://swift.org/blog/swift-3-0-release-process/) it would also be nice to add support for [SwiftPM](https://swift.org/package-manager/)

Articles about **SwiftPM**:
- [Package.swift — The Manifest File](https://github.com/apple/swift-package-manager/blob/master/Documentation/Package.swift.md)
- [Developing Packages](https://github.com/apple/swift-package-manager/blob/master/Documentation/DevelopingPackages.md)
- [System Modules](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md)
- [Swift Package Manager Community Proposal](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md)

On your `README.md` add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top and add section for the installation with SwiftPM.

**Comment by jvisenti** [comment]
Swift 3 support in progress see #7

**Comment by ZevEisenberg** [comment]
Swift 3 support is now merged! I don't believe you can currently use SPM with iOS apps yet (am I mistaken?), and Anchorage depends on UIKit, so there currently wouldn't be much point in supporting SPM currently.

**Comment by DrBeta** [comment]
@ZevEisenberg Now SPM is going to be integrated with Xcode 11, you should probably add support for SPM

**Comment by ZevEisenberg** [comment]
I’d love to! If anyone has a little time to put together a draft PR for SwiftPM support, I’d love to look at it. Not sure when I’ll be able to get to it.

**Comment by needhamwoodj** [comment]
Closing Issue, SwiftPM support has been added.
