### ISSUE TITLE
Update for Swift 5.0

### ISSUE THREAD

**Issue by terenceyan** [Rightpoint/Anchorage#74]
On top of fixing up the `podspec` to include `swift_version` (#68) and fixing Xcode 10.2+ warnings (#73), this project should be updated to Swift 5.0.

I took a quick pass at this and it appears to only require a few minor changes. However, someone with access needs to fix the CI build (it currently points to an inaccessible CircleCI page).

**Comment by ZevEisenberg** [comment]
@terenceyan which build link are you talking about? We renamed our GitHub org recently, so we may need to clean up a few broken links. Thanks for taking the time to write in!

**Comment by terenceyan** [comment]
@ZevEisenberg The readme has a link to [https://circleci.com/gh/Raizlabs/Anchorage](url) which isn't accessible.

**Comment by ZevEisenberg** [comment]
Ah, good catch. That should be updated to https://circleci.com/gh/Rightpoint/Anchorage. Mind updating it in this PR?

**Comment by ZevEisenberg** [comment]
Update: updated 😄
