### ISSUE TITLE
Please Update for Swift 5.2

### ISSUE THREAD

**Issue by mlch911** [Rightpoint/Anchorage#91]
Anchorage won't work after updating xcode to 11.4 which is using swift 5.2.

import Anchorage cause an error :
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler.

**Comment by ZevEisenberg** [comment]
How are you importing Anchorage? We don’t distribute Anchorage as a binary, so most likely, you’ll need to rebuild it. This may be as simple as clearing your build folder or derived data. Or, if you’re using Carthage, you’ll probably need to rebuild the framework first.

**Comment by mlch911** [comment]
Sorry, I rebuild the framework and it works.
